---
name: Linting
on:
  pull_request:
    branches:
      - main

jobs:
  shell-lint:
    name: Shell Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0

  python-lint:
    name: Python Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          poetry install

      - name: Run Linters
        run: |
          flake8

  yaml-lint:
    name: YAML Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3
        with:
          configData: |
            extends: relaxed
            rules:
              line-length:
                max: 120
                level: warning
              document-start:
                present: true
              truthy:
                level: warning

  markdown-lint:
    name: Markdown Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Lint MD files
        uses: avto-dev/markdown-lint@v1
        with:
          args: './**/*.md'
