---
name: Linting
on:
  pull_request:
    branches:
      - main

jobs:
  shell-lint:
    name: Shell Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@2.0.0

  python-lint:
    name: Python Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install
          pip install flake8

      - name: Run Linters
        run: |
          flake8
